services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: postgres_db
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    container_name: pgadmin4
    depends_on:
      - db
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
